# Site settings
name: 不疯魔不成活
email: bennetyf@gmail.com
author: Feng Yuan
404notfound: /404/404.html
resume_site: /404/404.html
home_site: http://fyuan.webutu.com
github: https://github.com/bennetyf
baseurl: ""
description: 从一到无穷大
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不息;Coding不止
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
plugins: [jekyll-paginate]
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: bennetyf
highlighter: pygments

# Build settings
markdown: kramdown
kramdown:
    input: GFM

#WebSite Analysis
#baidu_analysis: 89d5828f62d1e46378c7ab7e7370b1ee

#Build Path
destination: /Users/Bennet/WorkSpace/Personal_Projects/GitPages/Chinese/fyuansite.github.io/_site
source: /Users/Bennet/WorkSpace/Personal_Projects/GitPages/Chinese/fyuansite.github.io

FY:
  comments :
    provider : fengyuan
    duoshuo:
        short_name : fyuan
    disqus :
        short_name : feng.yuan
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
